apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hcloud-ccm.serviceAccountName" . }}
  labels:
    {{- include "hcloud-ccm.labels" . | nindent 4 }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hcloud-ccm.serviceAccountName" . }}
  labels:
    {{- include "hcloud-ccm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "hcloud-ccm.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
