{{- if and .Values.initdbScripts (not .Values.initdbScriptsCM) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stolon.fullname" . }}-initdb
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
data:
  {{- with .Values.initdbScripts }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
