apiVersion: v1
kind: Service
metadata:
  name: {{ template "stolon.fullname" . }}-keeper-headless
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
    component: stolon-keeper
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.ports.stolon }}
      targetPort: stolon
      protocol: TCP
      name: stolon
    - port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "stolon.selectorLabels" . | nindent 4 }}
    component: stolon-keeper
