apiVersion: v1
kind: Service
metadata:
  name: {{ include "stolon.fullname" . }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
    component: stolon-proxy
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.ports.stolon }}
      targetPort: stolon
      protocol: TCP
      name: stolon
  selector:
    {{- include "stolon.selectorLabels" . | nindent 4 }}
    component: stolon-proxy
