kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hcloud-csi.fullname" . }}
  labels:
    {{- include "hcloud-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hcloud-csi.fullname" . }}
  labels:
    {{- include "hcloud-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hcloud-csi.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "hcloud-csi.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
