apiVersion: v1
kind: Service
metadata:
  name: {{ include "hcloud-csi.fullname" . }}-controller-metrics
  labels:
    {{- include "hcloud-csi.labels" . | nindent 4 }}
    component: controller
spec:
  ports:
    - port: 9189
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "hcloud-csi.selectorLabels" . | nindent 4 }}
    component: controller

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hcloud-csi.fullname" . }}-node-metrics
  labels:
    {{- include "hcloud-csi.labels" . | nindent 4 }}
    component: node
spec:
  ports:
    - port: 9189
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "hcloud-csi.selectorLabels" . | nindent 4 }}
    component: node
