apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "hcloud-csi.storageClassName" . }}
  labels:
    {{- include "hcloud-csi.labels" . | nindent 4 }}
  {{- if .Values.storageClass.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: csi.hetzner.cloud
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
